import 'package:ar_zoo_explorers/domain/entities/question_entity.dart';

List<QuestionEntity> questions = [
  QuestionEntity(
    correctAnswerIndex: 1,
    options: [
      'a) Madrid',
      'b) Paris',
      'c) Berlin',
      'd) Rome',
    ],
    categoryQuestion: '',
    question: 'Which animal is this?',
    image: '',
    answer: 'FOX',
    puzzles: [],
  ),
  QuestionEntity(
    correctAnswerIndex: 1,
    options: [
      'a) Madrid',
      'b) Paris',
      'c) Berlin',
      'd) Rome',
    ],
    categoryQuestion: '',
    question: '1. What is the capital of France?',
    image: '',
    answer: '',
    puzzles: [],
  ),
  QuestionEntity(
    correctAnswerIndex: 3,
    options: [
      'a) Europe',
      'b) Asia',
      'c) North America',
      'd) South America',
    ],
    categoryQuestion: '2. In what continent is Brazil located?',
    question: '',
    image: '',
    answer: '',
    puzzles: [],
  ),
  QuestionEntity(
    correctAnswerIndex: 1,
    options: [
      'a) Earth',
      'b) Jupiter',
      'c) Saturn',
      'd) Venus',
    ],
    categoryQuestion: '',
    question: '3. What is the largest planet in our solar system?',
    image: '',
    answer: '',
    puzzles: [],
  ),
  // QuestionEntity(
  //   questionEntity: '4. What is the longest river in the world?',
  //   correctAnswerIndex: 0,
  //   options: [
  //     'a) Nile',
  //     'b) Amazon',
  //     'c) Mississippi',
  //     'd) Danube',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '5. Who is the main character in the Harry Potter series?',
  //   correctAnswerIndex: 2,
  //   options: [
  //     'a) Hermione Granger',
  //     'b) Ron Weasley',
  //     'c) Harry Potter',
  //     'd) Neville Longbottom',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '6. What is the smallest planet in our solar system?',
  //   correctAnswerIndex: 3,
  //   options: [
  //     'a) Venus',
  //     'b) Mars',
  //     'c) Earth',
  //     'd) Mercury',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '7. Who wrote the play Romeo and Juliet?',
  //   correctAnswerIndex: 0,
  //   options: [
  //     'a) William Shakespeare',
  //     'b) Oscar Wilde',
  //     'c) Jane Austen',
  //     'd) Charles Dickens',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '8. What is the highest mountain in the world?',
  //   correctAnswerIndex: 1,
  //   options: [
  //     'a) Mont Blanc',
  //     'b) Everest',
  //     'c) Kilimanjaro',
  //     'd) Aconcagua',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity:
  //       '9. What is the name of the famous painting by Leonardo da Vinci that depicts a woman?',
  //   correctAnswerIndex: 3,
  //   options: [
  //     'a) Starry Night',
  //     'b) The Persistence of Memory',
  //     'c) The Last Supper',
  //     'd) Mona Lisa',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
];
