import 'package:ar_zoo_explorers/domain/entities/question_entity.dart';

List<QuestionEntity> questions = [
  QuestionEntity(
    // correctAnswerIndex: 1,
    options: [
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello1', "vi": "Xin chào1"},
      {"en": 'hello2', "vi": "Xin chào2"},
      {"en": 'hello3', "vi": "Xin chào3"}
    ],
    categoryQuestion: '',
    question: {'en': "Which animal is this?", 'vi': "Đây là con vật gì?"},
    image: 'assets/images/learning_image/puzzle/fox.png',
    answer: 'hello',
    puzzles: [],
    id: '',
    categoryId: '',
  ),
  QuestionEntity(
    // correctAnswerIndex: 1,
    options: [
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"}
    ],
    categoryQuestion: '',
    question: {'en': "Which animal is this?", 'vi': "Đây là con vật gì?"},
    image: '',
    answer: '',
    puzzles: [],
    id: '',
    categoryId: '',
  ),
  QuestionEntity(
    // correctAnswerIndex: 3,
    options: [
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"}
    ],
    categoryQuestion: '',
    question: {'en': "Which animal is this?", 'vi': "Đây là con vật gì?"},
    image: '',
    answer: '',
    puzzles: [],
    id: '',
    categoryId: '',
  ),
  QuestionEntity(
    // correctAnswerIndex: 1,
    options: [
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"},
      {"en": 'hello', "vi": "Xin chào"}
    ],
    categoryQuestion: '',
    question: {'en': "Which animal is this?", 'vi': "Đây là con vật gì?"},
    image: '',
    answer: '',
    puzzles: [],
    id: '',
    categoryId: '',
  ),
  // QuestionEntity(
  //   questionEntity: '4. What is the longest river in the world?',
  //   correctAnswerIndex: 0,
  //   options: [
  //     'a) Nile',
  //     'b) Amazon',
  //     'c) Mississippi',
  //     'd) Danube',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '5. Who is the main character in the Harry Potter series?',
  //   correctAnswerIndex: 2,
  //   options: [
  //     'a) Hermione Granger',
  //     'b) Ron Weasley',
  //     'c) Harry Potter',
  //     'd) Neville Longbottom',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '6. What is the smallest planet in our solar system?',
  //   correctAnswerIndex: 3,
  //   options: [
  //     'a) Venus',
  //     'b) Mars',
  //     'c) Earth',
  //     'd) Mercury',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '7. Who wrote the play Romeo and Juliet?',
  //   correctAnswerIndex: 0,
  //   options: [
  //     'a) William Shakespeare',
  //     'b) Oscar Wilde',
  //     'c) Jane Austen',
  //     'd) Charles Dickens',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity: '8. What is the highest mountain in the world?',
  //   correctAnswerIndex: 1,
  //   options: [
  //     'a) Mont Blanc',
  //     'b) Everest',
  //     'c) Kilimanjaro',
  //     'd) Aconcagua',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
  // QuestionEntity(
  //   questionEntity:
  //       '9. What is the name of the famous painting by Leonardo da Vinci that depicts a woman?',
  //   correctAnswerIndex: 3,
  //   options: [
  //     'a) Starry Night',
  //     'b) The Persistence of Memory',
  //     'c) The Last Supper',
  //     'd) Mona Lisa',
  //   ],
  //   categoryQuestion: '',
  //   question: '',
  //   image: '',
  //   answer: '',
  // ),
];
