# Generated code do not commit.
file(TO_CMAKE_PATH "C:\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "C:\\MY_WORKING\\NAM04_HK1\\TLCN\\ar_zoo_explorers" PROJECT_DIR)

set(FLUTTER_VERSION "1.0.0+1" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 1 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=C:\\flutter"
  "PROJECT_DIR=C:\\MY_WORKING\\NAM04_HK1\\TLCN\\ar_zoo_explorers"
  "FLUTTER_ROOT=C:\\flutter"
  "FLUTTER_EPHEMERAL_DIR=C:\\MY_WORKING\\NAM04_HK1\\TLCN\\ar_zoo_explorers\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=C:\\MY_WORKING\\NAM04_HK1\\TLCN\\ar_zoo_explorers"
  "FLUTTER_TARGET=C:\\MY_WORKING\\NAM04_HK1\\TLCN\\ar_zoo_explorers\\lib\\main_develop.dart"
  "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9iMjAxODNlMDQwOTYwOTRiY2MzN2Q5Y2RlMmE0Yjk2ZjVjYzY4NGNmLw=="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=C:\\MY_WORKING\\NAM04_HK1\\TLCN\\ar_zoo_explorers\\.dart_tool\\package_config.json"
)
